// <auto-generated />
namespace Project2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class genre2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genre2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605021540575_genre2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
